AWSTemplateFormatVersion: '2010-09-09'
Description: ALB + Target Group + HTTP Listener (minimal)

Parameters:
  Env:
    Type: String
    AllowedValues: [dev, qa, uat, prod]
  ProjectName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  PublicSubnetIds:
    Type: String
    Description: Comma-separated public subnet IDs
  AlbSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${ProjectName}-${Env}-alb'
      Type: application
      Scheme: internet-facing
      SecurityGroups:
        - !Ref AlbSecurityGroupId
      Subnets: !Split [",", !Ref PublicSubnetIds]
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Env
          Value: !Ref Env

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${ProjectName}-${Env}-tg'
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: 8080
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      Matcher:
        HttpCode: '200-399'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Env
          Value: !Ref Env

  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref Alb
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

Outputs:
  AlbDnsName:
    Value: !GetAtt Alb.DNSName
  HttpListenerArn:
    Value: !Ref HttpListener
  TargetGroupArn:
    Value: !Ref TargetGroup
