AWSTemplateFormatVersion: '2010-09-09'
Description: Security Groups - ALB + ECS

Parameters:
  Env:
    Type: String
    AllowedValues: [dev, qa, uat, prod]
  ProjectName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound HTTP to ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Env}-alb-sg'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Env
          Value: !Ref Env

  EcsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound from ALB to ECS tasks
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref AlbSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Env}-ecs-sg'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Env
          Value: !Ref Env

Outputs:
  AlbSecurityGroupId:
    Value: !Ref AlbSecurityGroup
  EcsSecurityGroupId:
    Value: !Ref EcsSecurityGroup
