version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install cfn-lint
  build:
    commands:
      - echo "Linting CloudFormation templates..."
      - cfn-lint aws-cfn-codepipeline/templates/root.yml
      - cfn-lint aws-cfn-codepipeline/templates/network/vpc.yml
      - cfn-lint aws-cfn-codepipeline/templates/security/sg.yml
      - cfn-lint aws-cfn-codepipeline/templates/alb/alb.yml
      - cfn-lint aws-cfn-codepipeline/templates/ecs/cluster-service.yml
      - cfn-lint aws-cfn-codepipeline/templates/s3/buckets.yml
      - cfn-lint aws-cfn-codepipeline/templates/lambda/functions.yml
      - aws cloudformation package --template-file aws-cfn-codepipeline/templates/root.yml --s3-bucket $CFN_PACKAGE_BUCKET ...


artifacts:
  files:
    - packaged-root.yml
    - params/*.json
