version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install cfn-lint

  build:
    commands:
      - cd aws-cfn-codepipeline
      - echo "Linting CloudFormation templates..."
      - cfn-lint templates/root.yml || true
      - cfn-lint templates/network/vpc.yml || true
      - cfn-lint templates/security/sg.yml || true
      - cfn-lint templates/alb/alb.yml || true
      - cfn-lint templates/ecs/cluster-service.yml || true
      - cfn-lint templates/s3/buckets.yml || true
      - cfn-lint templates/lambda/functions.yml || true

      - echo "CFN_PACKAGE_BUCKET=$CFN_PACKAGE_BUCKET"
      - aws s3 ls "s3://$CFN_PACKAGE_BUCKET" || true

      - echo "Packaging CloudFormation template..."
      - |
          aws cloudformation package \
            --template-file templates/root.yml \
            --s3-bucket "$CFN_PACKAGE_BUCKET" \
            --output-template-file packaged-root.yml

artifacts:
  files:
    - aws-cfn-codepipeline/packaged-root.yml
    - aws-cfn-codepipeline/params/*.json
