version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install cfn-lint
  build:
    commands:
      - echo "Linting CloudFormation templates..."
      - cfn-lint templates/root.yml
      - cfn-lint templates/network/vpc.yml
      - cfn-lint templates/security/sg.yml
      - cfn-lint templates/alb/alb.yml
      - cfn-lint templates/ecs/cluster-service.yml
      - cfn-lint templates/s3/buckets.yml
      - cfn-lint templates/lambda/functions.yml
      - echo "Packaging (uploads local assets to S3)..."
      - aws cloudformation package --template-file templates/root.yml --s3-bucket $CFN_PACKAGE_BUCKET --output-template-file packaged-root.yml

artifacts:
  files:
    - packaged-root.yml
    - params/*.json
