AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda (minimal) - Hello function (code from S3)

Parameters:
  Env:
    Type: String
    AllowedValues: [dev, qa, uat, prod]
  Workstream:
    Type: String
    Description: Workstream identifier
  ProjectName:
    Type: String
    Description: Application name
  LambdaCodeS3Bucket:
    Type: String
  LambdaCodeS3Key:
    Type: String

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'hq-${Workstream}-${Env}-${ProjectName}-Role-Lambda'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: Name
          Value: !Sub 'hq-${Workstream}-${Env}-${ProjectName}-Role-Lambda'
        - Key: Workstream
          Value: !Ref Workstream
        - Key: Project
          Value: !Ref ProjectName
        - Key: Env
          Value: !Ref Env

  HelloFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'hq-${Workstream}-${Env}-${ProjectName}-Lambda-Hello'
      Runtime: python3.11
      Handler: app.handler
      Role: !GetAtt LambdaRole.Arn
      Timeout: 10
      Code:
        S3Bucket: !Ref LambdaCodeS3Bucket
        S3Key: !Ref LambdaCodeS3Key
      Environment:
        Variables:
          ENV: !Ref Env
      Tags:
        - Key: Name
          Value: !Sub 'hq-${Workstream}-${Env}-${ProjectName}-Lambda-Hello'
        - Key: Workstream
          Value: !Ref Workstream
        - Key: Project
          Value: !Ref ProjectName
        - Key: Env
          Value: !Ref Env

Outputs:
  HelloFunctionArn:
    Value: !GetAtt HelloFunction.Arn
