AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for artifacts (private, encrypted)

Parameters:
  Env:
    Type: String
    AllowedValues: [dev, qa, uat, prod]
  ProjectName:
    Type: String

Resources:
  AppArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${Env}-artifacts-${AWS::AccountId}-${AWS::Region}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Env
          Value: !Ref Env

Outputs:
  AppArtifactsBucket:
    Value: !Ref AppArtifactsBucket
