AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for artifacts (private, encrypted)

Parameters:
  Env:
    Type: String
    AllowedValues: [dev, qa, uat, prod]
  Workstream:
    Type: String
    Description: Workstream identifier
  ProjectName:
    Type: String
    Description: Application name

Resources:
  AppArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'hq-${Workstream}-${Env}-${ProjectName}-s3-artifacts-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: !Sub 'hq-${Workstream}-${Env}-${ProjectName}-S3-Artifacts'
        - Key: Workstream
          Value: !Ref Workstream
        - Key: Project
          Value: !Ref ProjectName
        - Key: Env
          Value: !Ref Env

Outputs:
  AppArtifactsBucket:
    Value: !Ref AppArtifactsBucket
